name: Update Plugins-dev

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release-plugins-dev:
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: falco-distribution
      AWS_S3_PREFIX: plugins
      AWS_S3_REGION: eu-west-1

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout Plugins
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Build registry artifact tool
        working-directory: build/registry
        run: make

      # Build packages for amd64
      - name: Build amd64 packages
        run: make packages

      # Build packages for aarch64
      - uses: uraimo/run-on-arch-action@v2
        name: Build arm64 packages
        with:
          arch: aarch64
          distro: ubuntu_latest
          
          # Speeds up builds by storing container images in a GitHub package registry.
          githubToken: ${{ github.token }}

          # Mount root in the container
          dockerRunArgs: --volume ${{ github.host-workspace }} --platform linux/amd64

          # Dependencies
          install: |
            apt-get update && apt-get install -y --no-install-recommends build-essential git ca-certificates golang curl && apt-get clean
            update-ca-certificates
            git config --global --add safe.directory ${{ github.workspace }}

          run: make packeges

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::292999226676:role/terraform-20230120142903096000000002"
          aws-region: ${{ env.AWS_S3_REGION }}

      - name: Upload files to S3
        # uses AWS_S3_BUCKET, AWS_S3_PREFIX, AWS_S3_REGION environment variables
        working-directory: build/registry
        run: ./bin/registry upload-to-s3 dev