name: Release Plugins

on:
  push:
    tags:
      # semver
      - '[a-z]*[0-9]+.[0-9]+.[0-9]+*'

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
env:
  AWS_S3_BUCKET: falco-distribution
  AWS_S3_PREFIX: plugins
  AWS_S3_REGION: eu-west-1

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  extract-info:
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.regex-match.outputs.group1 }}
      
    steps:
      - name: Extract semver ℹ️
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.ref_name }}
          regex: '^([a-z]+[a-z0-9_\-]*)-(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?$'

  release-plugins-stable-x86:
    runs-on: ubuntu-latest
    needs: extract-info
    steps:
      - name: Checkout Plugins ⤵️
        uses: actions/checkout@v3

      - name: Setup Golang 🚀
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Build registry artifact tool 📒
        working-directory: build/registry
        run: make

      - name: Run x86 build 🏗️
        run: make release/${{ needs.extract-info.outputs.package }}

      - name: Configure AWS credentials 🔧⚙️
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::292999226676:role/terraform-20230120142903096000000002"
          aws-region: ${{ env.AWS_S3_REGION }}

      - name: Upload files to S3 ⬆️
        # uses AWS_S3_BUCKET, AWS_S3_PREFIX, AWS_S3_REGION environment variables
        working-directory: build/registry
        run: ./bin/registry upload-to-s3 stable

  release-plugins-stable-arm64:
    runs-on: ubuntu-latest
    needs: extract-info
    steps:
      - name: Checkout Plugins ⤵️
        uses: actions/checkout@v3
      
      - name: Run arm64 build 🏗️
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}

          install: |
            apt-get update && apt-get install -y --no-install-recommends build-essential git ca-certificates golang curl && apt-get clean
            update-ca-certificates
            git config --global --add safe.directory ${{ github.workspace }}
            
          run: make release/${{ needs.extract-info.outputs.package }}
          
      - name: Configure AWS credentials 🔧⚙️
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::292999226676:role/terraform-20230120142903096000000002"
          aws-region: ${{ env.AWS_S3_REGION }}

      - name: Upload files to S3 ⬆️
        # uses AWS_S3_BUCKET, AWS_S3_PREFIX, AWS_S3_REGION environment variables
        working-directory: build/registry
        run: ./bin/registry upload-to-s3 stable