name: Release Plugins

on:
  push:
    tags:
      # semver
      - '[a-z]*[0-9]+.[0-9]+.[0-9]+'
jobs:
  release-plugins-stable:
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: falco-distribution
      AWS_S3_PREFIX: plugins
      AWS_S3_REGION: eu-west-1

    steps:
      - name: Checkout Plugins
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Build registry artifact tool
        working-directory: build/registry
        run: make

      # Build only tagget packages: extract the semver groups
      - name: Extract semver
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.ref_name }}
          regex: '^([a-z]+[a-z0-9_\-]*)-(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?$'

      # Takes only the first group of the match for the tagged package
      - name: Build release packages
        run: make release/${{ steps.regex-match.outputs.group1 }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::292999226676:role/terraform-20230120142903096000000002"
          aws-region: ${{ env.AWS_S3_REGION }}

      - name: Upload files to S3
        # uses AWS_S3_BUCKET, AWS_S3_PREFIX, AWS_S3_REGION environment variables
        working-directory: build/registry
        run: ./bin/registry upload-to-s3 stable